### ISSUE TITLE
Add link to breadcrumbs

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/azera-shop#83]
@rodica-andronache client said this was possible in past releases but latest update does not have it: 

http://themeisle.com/wp-content/uploads/gravity_forms/1-a802f9b942a19180d258d8ed48e41d68/2016/10/Line-under-logo.jpg

**Comment by rodica-andronache** [comment]
@UVLabs I'm not sure about this. The only section where I think we have breadcrumbs is the shop page http://demo.themeisle.com/azera-shop/product/bacon-and-egg-cupcakes/.

Is he talking about the shop/single page or other one. Was he using maybe a plugin for this? And it's not compatible anymore? 
We need more details here

**Comment by KoKane81** [comment]
@UVLabs 
I'm talking about the shop page.
The function is working on your link, but it is not working after the update in my shop.
https://knabberkiste-shop.de/produkt-kategorie/kauartikel/rind
I can't use the link "Kauartikel"

**Comment by rodica-andronache** [comment]
Hi @KoKane81 ,

Thank you for contacting us. I checked your site and you are right. We have an issue with the breadcrumbs , when you also have a background image selected. 
We'll investigate the issue and release an update as soon as possible.

Regards,
Rodica

@claudiuvertistudio can you please have a look here ? I think the issue is caused by this line https://github.com/Codeinwp/azera-shop/blob/769aa5974b301cef059869329bc081788392f4d3/js/custom.all.js#L487 . You can test the issue here http://dev2.themeisle.com/azera-shop/shop/ too.

**Comment by rodica-andronache** [comment]
Hi @KoKane81 ,

We just released an update to fix this issue. Please update and let me know if everything is ok now.
Thank you again for reporting this.

Regards,
Rodica

**Comment by KoKane81** [comment]
Hi @rodica-andronache ,
thanks for your help, now it is working fine.

**Comment by rodica-andronache** [comment]
Hi @KoKane81 ,

I'm glad to hear everything is ok. Let us know if we can help with anything else.
Also, thank you very much for your review. It helps us a lot.

Regards,
Rodica
